## 87.75 점

In [1]:
import warnings
import pandas as pd
import numpy as np
import cv2

from keras.models import Model
from keras.layers import Flatten, Dense, Input, Conv2D, MaxPooling2D
from keras.layers import GlobalAveragePooling2D, GlobalMaxPooling2D, TimeDistributed
from keras.engine.topology import get_source_inputs
from keras.utils import layer_utils, to_categorical
from keras import backend as K
from keras import optimizers

Using TensorFlow backend.
/home/pirl/anaconda3/envs/vnect/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/pirl/anaconda3/envs/vnect/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/pirl/anaconda3/envs/vnect/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/pirl/anaconda3/envs/vne

In [2]:
# load dataset list

train_data = pd.read_csv("train_vision.csv")
train_filename = train_data["filename"].values.tolist()
train_data["label"] = train_data["label"] -1
train_label = train_data["label"].values.tolist()

test_data = pd.read_csv("test_vision.csv")
test_filename = test_data["filename"].values.tolist()

print(len(train_filename), len(train_label), len(test_filename))

5850 5850 2000


In [3]:
print(train_data['label'].head())

0    0
1    3
2    3
3    3
4    3
Name: label, dtype: int64


In [3]:
# load train data
input_height , input_width = 128, 128
n_class = 6

def getImageArr(img_name):
        img = cv2.imread("faces_images/" + img_name, 1)
        img = np.float32(img) / 127.5 - 1   #0~255 를 평균 0이게 수정
        return img

X = []
for name in train_filename:
    X.append(getImageArr(name))
    
X, Y = np.array(X), to_categorical(np.array(train_label),n_class)
print(X.shape, Y.shape)

(5850, 128, 128, 3) (5850, 6)


In [68]:
print(Y)

[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 ...
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]


In [4]:
# split dataset

train_rate = 0.85
index_train = np.random.choice(X.shape[0],int(X.shape[0]*train_rate),replace=False)
index_test  = list(set(range(X.shape[0])) - set(index_train))
                            
# X, Y = shuffle(X,Y)
X_train, y_train = X[index_train],Y[index_train]
X_test, y_test = X[index_test],Y[index_test]
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(4972, 128, 128, 3) (4972, 6)
(878, 128, 128, 3) (878, 6)


In [5]:
# load test data

real_test = []
for name in test_filename:
    real_test.append(getImageArr(name))
    
real_test = np.array(real_test)
print(real_test.shape)

(2000, 128, 128, 3)


In [6]:
 def nn_base(nClasses, input_height=128, input_width=128):
        
    img_input = Input(shape=(input_height,input_width, 3))
        
    # Block 1
    x = Conv2D(64, (3, 3), activation='relu', padding='same', name='block1_conv1')(img_input)
    x = Conv2D(64, (3, 3), activation='relu', padding='same', name='block1_conv2')(x)
    x = MaxPooling2D((2, 2), strides=(2, 2), name='block1_pool')(x)  #64*64

    # Block 2
    x = Conv2D(128, (3, 3), activation='relu', padding='same', name='block2_conv1')(x)
    x = Conv2D(128, (3, 3), activation='relu', padding='same', name='block2_conv2')(x)
    x = MaxPooling2D((2, 2), strides=(2, 2), name='block2_pool')(x)  #32*32

    # Block 3
    x = Conv2D(256, (3, 3), activation='relu', padding='same', name='block3_conv1')(x)
    x = Conv2D(256, (3, 3), activation='relu', padding='same', name='block3_conv2')(x)
    x = Conv2D(256, (3, 3), activation='relu', padding='same', name='block3_conv3')(x)
    x = MaxPooling2D((2, 2), strides=(2, 2), name='block3_pool')(x)    #16*16

    # Block 4
    x = Conv2D(512, (3, 3), activation='relu', padding='same', name='block4_conv1')(x)
    x = Conv2D(512, (3, 3), activation='relu', padding='same', name='block4_conv2')(x)
    x = Conv2D(512, (3, 3), activation='relu', padding='same', name='block4_conv3')(x)
    x = MaxPooling2D((2, 2), strides=(2, 2), name='block4_pool')(x)    #8*8*512

    # Block 5
    x = Conv2D(512, (3, 3), activation='relu', padding='same', name='block5_conv1')(x)
    x = Conv2D(512, (3, 3), activation='relu', padding='same', name='block5_conv2')(x)
    x = Conv2D(512, (3, 3), activation='relu', padding='same', name='block5_conv3')(x)
    # x = MaxPooling2D((2, 2), strides=(2, 2), name='block5_pool')(x)
    
    # classification
    x = Flatten(name='flatten')(x)
    x = Dense(4096, activation='relu', name='fc1')(x)
    
    x = Dense(4096, activation='relu', name='fc2')(x)
    
    x = Dense(n_class , activation='softmax', name='predictions')(x)
    
    model = Model(img_input, x)

    return model

In [8]:
model = nn_base(nClasses  = n_class,  
             input_height = 128, 
             input_width  = 128)
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 128, 128, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 128, 128, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 128, 128, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 64, 64, 64)        0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 64, 64, 128)       73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 64, 64, 128)       147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 32, 32, 128)       0         
__________

In [49]:
sgd = optimizers.SGD(lr=1E-2, decay=5**(-4), momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

hist1 = model.fit(X_train,y_train,
                  validation_data=(X_test,y_test),
                  batch_size=32,epochs=15)

Train on 4972 samples, validate on 878 samples
Epoch 1/15
4972/4972 [==============================] - 25s 5ms/step - loss: 0.6275 - acc: 0.7860 - val_loss: 0.4481 - val_acc: 0.8405
Epoch 2/15
4972/4972 [==============================] - 21s 4ms/step - loss: 0.3358 - acc: 0.8759 - val_loss: 0.4263 - val_acc: 0.8508
Epoch 3/15
4972/4972 [==============================] - 21s 4ms/step - loss: 0.2469 - acc: 0.9071 - val_loss: 0.4403 - val_acc: 0.8588
Epoch 4/15
4972/4972 [==============================] - 21s 4ms/step - loss: 0.1720 - acc: 0.9366 - val_loss: 0.4676 - val_acc: 0.8770
Epoch 5/15
4972/4972 [==============================] - 22s 4ms/step - loss: 0.1244 - acc: 0.9556 - val_loss: 0.4399 - val_acc: 0.8656
Epoch 6/15
4972/4972 [==============================] - 21s 4ms/step - loss: 0.0758 - acc: 0.9753 - val_loss: 0.6146 - val_acc: 0.8645
Epoch 7/15
4972/4972 [==============================] - 22s 4ms/step - loss: 0.0578 - acc: 0.9795 - val_loss: 0.5330 - val_acc: 0.8679
Epoch 8/

In [ ]:
for key in ['loss', 'val_loss']:
    plt.plot(hist1.history[key],label=key)
plt.legend()
plt.show()

In [67]:
y_pred = model.predict(real_test)
y_predi = np.argmax(y_pred,axis = 1) + 1
print(np.unique(y_predi), y_predi.shape)

[1 2 3 4 5 6] (2000,)


In [73]:
y_predi.dtype

dtype('int64')

In [74]:
np.savetxt("1-2.csv", y_predi, delimiter=",", fmt='%i')

In [97]:
answer = pd.DataFrame({"prediction":y_predi})

In [104]:
answer.to_csv('1-1.csv',index=False, header="label")

In [92]:
answer.tail()

prediction
1995           1
1996           1
1997           5
1998           4
1999           1

In [128]:
a = pd.read_csv('1-1.csv').reset_index()
b = pd.read_csv('test_vision.csv').reset_index()
c = pd.merge(a,b, on='index')
c[:50]

index  prediction       filename
0       0           1  face_2624.png
1       1           1  face_3385.png
2       2           1  face_5015.png
3       3           1  face_6715.png
4       4           4  face_6171.png
5       5           4  face_3269.png
6       6           4  face_4942.png
7       7           5  face_1095.png
8       8           4  face_7721.png
9       9           1  face_2455.png
10     10           4  face_6595.png
11     11           5  face_2024.png
12     12           4  face_1232.png
13     13           2  face_3796.png
14     14           4  face_4859.png
15     15           4    face_67.png
16     16           4  face_5667.png
17     17           1  face_2672.png
18     18           1  face_6755.png
19     19           1  face_5293.png
20     20           1  face_3996.png
21     21           4  face_7237.png
22     22           4   face_925.png
23     23           4   face_566.png
24     24           4  face_2910.png
25     25           5   face_266.png
26     26           4   face_611.png
27     27           4  face_5727.png
28     28           1  face_5443.png
29     29           1  face_5894.png
30     30           4  face_7963.png
31     31           1  face_5595.png
32     32           4  face_6896.png
33     33           4  face_3918.png
34     34           2  face_5286.png
35     35           2  face_2544.png
36     36           1  face_6850.png
37     37           4  face_4607.png
38     38           2  face_5386.png
39     39           6  face_7531.png
40     40           3  face_1924.png
41     41           4  face_4330.png
42     42           4   face_645.png
43     43           1  face_6040.png
44     44           1  face_4227.png
45     45           1  face_6876.png
46     46           4  face_4592.png
47     47           6  face_1092.png
48     48           3  face_2042.png
49     49           1  face_2531.png